### ISSUE TITLE
genetic horizon aggregation updates

### ISSUE THREAD

**Issue by brownag** [ncss-tech/tiledConusProcessing#1]
Some notes following on from recent testing of genetic horizon aggregation for CONUS mukey grid

https://github.com/ncss-tech/tiledConusProcessing/blob/e6ac6f1352c9b423643bf00f64c516cdf147c7be/examples/genetic-hz-horizons-comppct.R#L51-L52

For additional `writeRaster()` options you want to use `wopt=list(datatype="INT1U")`. Current code gives error: `Error in fun(v, ...) : unused argument (datatype = "INT1U")`

Also, to export the function to multiple compute nodes, supply the user-defined function as an argument to an anonymous function applied by `app()`, i.e.:

```r
system.time(r <- app(g, fun = function(i, ff) ff(i), 
                     cores = 1,
                     ff = .f,
                     filename = 'E-horizon-pct_BYTE.tif', 
                     overwrite = TRUE, 
                     wopt = list(datatype = "INT1U")))
```

While this is the pattern to make the `cores > 1` argument work, in my experience on the work computer it is not as fast as `cores=1`

**Comment by dylanbeaudette** [comment]
Thanks
